file utils for image creation and handling files
OmerLevy1248/wake-me-home pull request #22
Opened 2019-10-24 19:45 UTC by Yuvalkeidar

2019-10-25 12:02 UTC, OmerLevy1248 requested changes
Those are very small changes but in the long run it helps to keep the code more readable. The most important is the one inside the onClick method of DetailActivity.

2019-10-25 12:02 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/DetailActivity.java
> +            fileUtils.deleteTempImage();
Why not inside of method "updateMapImageVisibility" that is responsible for everything related to the mapImage?

2019-10-25 12:02 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/DetailActivity.java
> +        String imgPath = !isExistPath(tempImagePath) ? fileUtils.getMapImagePath(mAlarmId) : tempImagePath;
Rename: isExistPath -> isPathExists for better english

2019-10-25 12:02 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/utilities/Constants.java
> +    public static final String TEMP_IMAGE_FILE = "temp.png";
Rename: TEMP_IMAGE_FILE -> TEMP_IMAGE_FILE_NAME

2019-10-25 12:02 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/utilities/fileUtils.java
> +public class fileUtils {
Why don't you use "/**<Enter>" for method comments? It will be easier to notice start of methods

2019-10-25 12:02 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/utilities/fileUtils.java
> +
Visually separate public section (class API) from private section (class logic) - it helps newcomers to understand the class better

2019-10-25 12:38 UTC, Yuvalkeidar commented on app/src/main/java/com/gusta/wakemehome/DetailActivity.java
> +            fileUtils.deleteTempImage();
Cause its not related to ui.. It happened on delete cause we want to delete resources that related to map image

2019-10-25 13:06 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/DetailActivity.java
> +            fileUtils.deleteTempImage();
But why did you separate the "visibility" and "file" update of the mapImage - a single method handling all mapImage will help avoid future bugs (when logic is changed/moved we may forget one of the call for example). The DetailActivity is not familiar with the necessities of the map, so from it's point of view the map should have one "doYourJob()" method.

2019-10-25 13:08 UTC, Yuvalkeidar commented on app/src/main/java/com/gusta/wakemehome/DetailActivity.java
> +            fileUtils.deleteTempImage();
No, it's related to ui only, show-hide there isn't manipulation on the file

2019-10-26 09:17 UTC, OmerLevy1248 approved these changes

2019-10-26 09:17 UTC, OmerLevy1248 commented on app/src/main/java/com/gusta/wakemehome/utilities/fileUtils.java
> +
I think something more prominent is better 
(like: 
///////////////////////////
// PRIVATE METHODS //
//////////////////////////
) - but it is not approve-blocking...

2019-10-26 09:37 UTC, merged